# Generated by Django 4.2.1 on 2023-08-04 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Brend',
        ),
        migrations.AlterField(
            model_name='wheel',
            name='image',
            field=models.ImageField(upload_to='news-wheel/'),
        ),
    ]
