# Generated by Django 5.0 on 2024-01-10 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_inventory'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='is_filter',
            field=models.BooleanField(default=False, verbose_name='Фильтровать'),
        ),
    ]
