# Generated by Django 5.0 on 2024-01-10 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_attributevalue_is_filter'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='is_filter',
        ),
        migrations.AddField(
            model_name='attribute',
            name='is_filter',
            field=models.BooleanField(default=False, verbose_name='Фильтровать'),
        ),
    ]
