# Generated by Django 5.0 on 2024-01-15 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_attribute_slug_attributevalue_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attributevalue',
            name='slug',
        ),
    ]
