# Generated by Django 5.0 on 2024-01-15 10:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0008_attributevalue_value_en'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attributevalue',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.attribute', verbose_name='Атрибут'),
        ),
        migrations.AlterField(
            model_name='attributevalue',
            name='value_en',
            field=models.CharField(blank=True, max_length=100, verbose_name='Значение EN'),
        ),
    ]
