# Generated by Django 5.0.1 on 2024-01-22 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0009_alter_attributevalue_attribute_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'Атрибут', 'verbose_name_plural': 'Атрибуты'},
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together=set(),
        ),
        migrations.RemoveField(
            model_name='attribute',
            name='is_filter',
        ),
        migrations.AddField(
            model_name='attribute',
            name='unit',
            field=models.CharField(blank=True, max_length=10, verbose_name='Единица измерения'),
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='is_main',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='unit',
        ),
        migrations.RemoveField(
            model_name='attributevalue',
            name='variant',
        ),
        migrations.CreateModel(
            name='AttributeVariant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_main', models.BooleanField(default=False, verbose_name='Отображать в названии')),
                ('is_filter', models.BooleanField(default=True, verbose_name='Отображать в фильтре')),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.attribute', verbose_name='Атрибут')),
                ('value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='store.attributevalue', verbose_name='Значение')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attributes', to='store.productvariant', verbose_name='Вариация продукта')),
            ],
            options={
                'verbose_name': 'Атрибут варианта товара',
                'verbose_name_plural': 'Атрибуты варианта товара',
                'unique_together': {('variant', 'attribute')},
            },
        ),
    ]
