# Generated by Django 5.0.1 on 2024-01-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0010_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Warehouse',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('address_line', models.TextField(max_length=254)),
            ],
            options={
                'verbose_name': 'Склад',
                'verbose_name_plural': 'Склад',
            },
        ),
        migrations.AlterField(
            model_name='attributevariant',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_variants', to='store.productvariant', verbose_name='Вариация продукта'),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_variant',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='store.productvariant'),
        ),
        migrations.AddField(
            model_name='inventory',
            name='warehouse',
            field=models.OneToOneField(default='', on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='store.warehouse'),
            preserve_default=False,
        ),
    ]
