# Generated by Django 5.0.1 on 2024-01-29 19:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0011_warehouse_alter_attributevariant_variant_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventory',
            name='warehouse',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='store.warehouse'),
        ),
    ]
