# Generated by Django 5.0.1 on 2024-02-01 14:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0015_alter_inventory_warehouse'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name': 'Склады', 'verbose_name_plural': 'Склад'},
        ),
        migrations.AlterField(
            model_name='inventory',
            name='product_variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='inventory', to='store.productvariant'),
        ),
    ]
