# Generated by Django 5.0.1 on 2024-06-08 23:52

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0016_alter_warehouse_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='attributevalue',
            options={'verbose_name': 'Значение атрибута', 'verbose_name_plural': 'Значения атрибутов'},
        ),
        migrations.AddField(
            model_name='productvariant',
            name='old_price',
            field=models.DecimalField(decimal_places=2, default=1000, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Старая цена'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='attributevariant',
            name='attribute',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_variants', to='store.attribute', verbose_name='Атрибут'),
        ),
        migrations.AlterField(
            model_name='attributevariant',
            name='value',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.attributevalue', verbose_name='Значение'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(Decimal('1'))], verbose_name='Цена'),
        ),
    ]
