# Generated by Django 5.0.1 on 2024-06-08 23:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0017_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='is_discounted',
            field=models.BooleanField(default=False, verbose_name='Скидка'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Старая цена'),
        ),
    ]
