# Generated by Django 5.2.5 on 2025-09-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='wb_article',
        ),
        migrations.AddField(
            model_name='variant',
            name='ozon_sku',
            field=models.BigIntegerField(blank=True, null=True, verbose_name='OZON SKU'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='ozon_article',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='OZON Артикул'),
        ),
    ]
