# Generated by Django 5.1.6 on 2025-09-01 20:59

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_variant_old_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
    ]
