# Generated by Django 5.2.5 on 2025-09-07 22:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_remove_variant_wb_article_variant_ozon_sku_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='ozon_sku',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='OZON SKU'),
        ),
    ]
