# Generated by Django 5.1.6 on 2025-09-01 21:04

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_variant_id'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='variant',
            name='products_va_sku_5451be_idx',
        ),
        migrations.RemoveField(
            model_name='product',
            name='sku',
        ),
        migrations.RemoveField(
            model_name='variant',
            name='sku',
        ),
        migrations.AlterField(
            model_name='product',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['id'], name='products_va_id_e2ed55_idx'),
        ),
    ]
