# Generated by Django 5.2.5 on 2025-09-08 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_alter_variant_ozon_sku'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='wb_article',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='WB Артикул'),
        ),
    ]
