# Generated by Django 5.2.5 on 2025-09-08 14:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_variant_wb_article'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ('title',), 'verbose_name': 'Категория', 'verbose_name_plural': 'Категории'},
        ),
        migrations.RemoveField(
            model_name='category',
            name='name',
        ),
        migrations.RemoveField(
            model_name='category',
            name='second_name',
        ),
        migrations.AddField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, default='', max_length=200, unique=True, verbose_name='Название (основное)'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='category',
            name='title_plural',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название во множественном числе'),
        ),
        migrations.AddField(
            model_name='category',
            name='title_singular',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Название в единственном числе'),
        ),
        migrations.AlterField(
            model_name='category',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category', verbose_name='Родительская категория'),
        ),
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(max_length=200, unique=True, verbose_name='URL-ключ'),
        ),
    ]
