# Generated by Django 5.2.5 on 2025-09-02 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_remove_variant_products_va_sku_5451be_idx_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True),
        ),
    ]
