# Generated by Django 5.2.5 on 2025-09-08 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_category_options_remove_category_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='slug',
            field=models.SlugField(unique=True, verbose_name='URL-ключ'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title',
            field=models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Название (основное)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_plural',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название (мн.ч.)'),
        ),
        migrations.AlterField(
            model_name='category',
            name='title_singular',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Название (ед.ч.)'),
        ),
    ]
