# Generated by Django 5.2.5 on 2025-09-02 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_variant_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='variant',
            name='inventory',
            field=models.PositiveIntegerField(default=0, verbose_name='В наличии:'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Активный'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='new',
            field=models.BooleanField(default=True, verbose_name='Бейджик NEW'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='old_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Старая цена'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='ozon_article',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Артикул озон'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='rec',
            field=models.BooleanField(default=False, verbose_name='Показывать на главной'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='wb_article',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Артикул вб'),
        ),
    ]
