# Generated by Django 5.2.5 on 2025-09-03 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_alter_variant_inventory_alter_variant_is_active_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='volume',
        ),
        migrations.AlterField(
            model_name='product',
            name='weight',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Вес для доставки, г'),
        ),
    ]
