# Generated by Django 5.2.5 on 2025-09-08 15:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_alter_attributevalue_unique_together_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='categoryattribute',
            name='is_required',
        ),
    ]
