# Generated by Django 5.2.5 on 2025-09-08 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_remove_categoryattribute_is_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='variant',
            name='ozon_sku',
        ),
        migrations.AddField(
            model_name='variant',
            name='seller_article',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Артикул продавца'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='ozon_article',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Артикул OZON'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='wb_article',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='Артикул WB'),
        ),
    ]
