# Generated by Django 5.1.15 on 2026-09-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0011_taobaoimportitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='fulfillment_type',
            field=models.CharField(choices=[('stock', 'В наличии'), ('preorder', 'Предзаказ')], db_index=True, default='stock', max_length=16, verbose_name='Тип продажи'),
        ),
        migrations.AddField(
            model_name='variant',
            name='preorder_days_max',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='Срок предзаказа до, дней'),
        ),
        migrations.AddField(
            model_name='variant',
            name='preorder_days_min',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Срок предзаказа от, дней'),
        ),
    ]
