# Generated by Django 5.1.15 on 2026-09-24 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0012_variant_fulfillment_type_variant_preorder_days_max_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='sales_unit',
            field=models.CharField(choices=[('piece', 'Штука'), ('pair', 'Пара')], default='piece', max_length=8, verbose_name='Единица продажи'),
        ),
    ]
