# Generated by Django 5.1.15 on 2026-09-24 16:00

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0013_variant_sales_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='variant',
            name='preorder_variant',
            field=models.OneToOneField(blank=True, help_text='Более дешёвая позиция, которую можно заказать с ожиданием.', limit_choices_to={'fulfillment_type': 'preorder'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_offer', to='products.variant', verbose_name='Вариант для предзаказа'),
        ),
    ]
