# Generated by Django 5.1.15 on 2026-09-24 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0014_variant_preorder_offer'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreorderVariant',
            fields=[
            ],
            options={
                'verbose_name': 'Товар по предзаказу',
                'verbose_name_plural': 'Товары по предзаказу',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.variant',),
        ),
        migrations.CreateModel(
            name='StockVariant',
            fields=[
            ],
            options={
                'verbose_name': 'Товар в наличии',
                'verbose_name_plural': 'Товары в наличии',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('products.variant',),
        ),
    ]
