# Generated by Django 5.1.15 on 2026-09-24 21:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0015_split_admin_catalogs'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preordervariant',
            options={'verbose_name': 'Товар по под заказу', 'verbose_name_plural': 'Товары по под заказу'},
        ),
        migrations.AlterField(
            model_name='variant',
            name='fulfillment_type',
            field=models.CharField(choices=[('stock', 'В наличии'), ('preorder', 'Под заказ')], db_index=True, default='stock', max_length=16, verbose_name='Тип продажи'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='preorder_days_max',
            field=models.PositiveSmallIntegerField(default=45, verbose_name='Срок заказа до, дней'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='preorder_days_min',
            field=models.PositiveSmallIntegerField(default=30, verbose_name='Срок заказа от, дней'),
        ),
        migrations.AlterField(
            model_name='variant',
            name='preorder_variant',
            field=models.OneToOneField(blank=True, help_text='Более дешёвая позиция, которую можно заказать с ожиданием.', limit_choices_to={'fulfillment_type': 'preorder'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='stock_offer', to='products.variant', verbose_name='Вариант для заказа'),
        ),
    ]
