# Generated by Django 5.0 on 2023-12-30 16:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('telegram_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram Id')),
                ('telegram_username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram Username')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперюзер?')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.PositiveIntegerField(unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('processing', 'В обработке'), ('goes_to_point', 'Едет в пункт выдачи'), ('shipped', 'Отправлен'), ('ready_for_shipping', 'Готов к выдаче'), ('canceled', 'Отменен'), ('completed', 'Завершен')], default='created', max_length=200, verbose_name='Статус')),
                ('user_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('order_notes', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('receiving_method', models.CharField(blank=True, choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=200, null=True, verbose_name='Метод получения')),
                ('delivery_method', models.CharField(blank=True, choices=[('russian_post', 'Почта России'), ('sdek', 'Сдек'), ('boxberry', 'Boxberry')], max_length=200, null=True, verbose_name='Способ доставки')),
                ('delivery_address', models.TextField(blank=True, null=True, verbose_name='Адрес доставки')),
                ('pickup_location', models.CharField(blank=True, choices=[('alekseevskaya', 'Алексеевская'), ('colntsevo', 'Солнцево')], max_length=100, null=True, verbose_name='Пункт самовывоза')),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код для отслеживания')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказов',
            },
        ),
    ]
