# Generated by Django 4.2.1 on 2023-07-21 16:12

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=254, unique=True, verbose_name='Почта')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперюзер?')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('Создан', 'Создан'), ('В обработке', 'В обработке'), ('В доставке', 'В доставке'), ('Готов к выдаче', 'Готов к выдаче'), ('Отменен', 'Отменен'), ('Завершен', 'Завершен')], default='Создан', max_length=200, verbose_name='Статус')),
                ('order_id', models.PositiveIntegerField()),
                ('first_name', models.CharField(max_length=200, verbose_name='Имя')),
                ('middle_name', models.CharField(max_length=200, verbose_name='Фамилия')),
                ('last_name', models.CharField(blank=True, max_length=200, verbose_name='Отчество')),
                ('address', models.CharField(blank=True, max_length=200, null=True, verbose_name='Адрес')),
                ('city', models.CharField(blank=True, max_length=200, null=True, verbose_name='Город')),
                ('phone_number', models.CharField(max_length=200, verbose_name='Телефон')),
                ('zip_code', models.CharField(blank=True, max_length=200, null=True, verbose_name='Индекс')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='accounts.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.product')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказов',
            },
        ),
    ]
