# Generated by Django 5.0 on 2024-01-04 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='username',
            field=models.CharField(default='Пользователь', max_length=30, verbose_name='Имя пользователя'),
        ),
    ]
