# Generated by Django 4.2.1 on 2023-08-07 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='delivery_value',
            field=models.CharField(blank=True, choices=[('Почта России', 'Почта России'), ('Сдек', 'Сдек'), ('Boxberry', 'Boxberry')], max_length=200, null=True, verbose_name='Способ доставки'),
        ),
    ]
