# Generated by Django 4.2.1 on 2023-08-07 20:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_order_delivery_value'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram'),
        ),
    ]
