# Generated by Django 4.2.1 on 2023-08-07 20:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_telegram_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='telegram_username',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram Username'),
        ),
        migrations.AlterField(
            model_name='user',
            name='telegram_id',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram Id'),
        ),
    ]
