# Generated by Django 4.2.1 on 2023-08-12 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_telegram_username_alter_user_telegram_id'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={},
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='city',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_value',
        ),
        migrations.RemoveField(
            model_name='order',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='middle_name',
        ),
        migrations.RemoveField(
            model_name='order',
            name='phone_number',
        ),
        migrations.RemoveField(
            model_name='order',
            name='zip_code',
        ),
        migrations.AddField(
            model_name='order',
            name='contact_phone',
            field=models.CharField(default=1, max_length=20, verbose_name='Телефон'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_address',
            field=models.TextField(blank=True, null=True, verbose_name='Адрес доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='delivery_method',
            field=models.CharField(blank=True, choices=[('russian_post', 'Почта России'), ('sdek', 'Сдек'), ('boxberry', 'Boxberry')], max_length=200, null=True, verbose_name='Способ доставки'),
        ),
        migrations.AddField(
            model_name='order',
            name='order_notes',
            field=models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу'),
        ),
        migrations.AddField(
            model_name='order',
            name='pickup_location',
            field=models.CharField(blank=True, choices=[('alekseevskaya', 'Алексеевская'), ('colntsevo', 'Солнцево')], max_length=100, null=True, verbose_name='Пункт самовывоза'),
        ),
        migrations.AddField(
            model_name='order',
            name='receiving_method',
            field=models.CharField(blank=True, choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=200, null=True, verbose_name='Метод получения'),
        ),
        migrations.AddField(
            model_name='order',
            name='tracking_code',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Код для отслеживания'),
        ),
        migrations.AddField(
            model_name='order',
            name='user_name',
            field=models.CharField(default=1, max_length=200, verbose_name='ФИО'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='order',
            name='order_id',
            field=models.PositiveIntegerField(unique=True, verbose_name='Номер заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('processing', 'В обработке'), ('shipped', 'Отправлен'), ('ready_for_shipping', 'Готов к выдаче'), ('canceled', 'Отменен'), ('completed', 'Завершен')], default='Создан', max_length=200, verbose_name='Статус'),
        ),
    ]
