# Generated by Django 4.2.1 on 2023-08-13 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_alter_order_options_remove_order_address_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Заказ', 'verbose_name_plural': 'Заказы'},
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('processing', 'В обработке'), ('goes_to_point', 'Едет в пункт выдачи'), ('shipped', 'Отправлен'), ('ready_for_shipping', 'Готов к выдаче'), ('canceled', 'Отменен'), ('completed', 'Завершен')], default='Создан', max_length=200, verbose_name='Статус'),
        ),
    ]
