# Generated by Django 4.2.1 on 2023-08-13 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_order_options_alter_order_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Создан'), ('processing', 'В обработке'), ('goes_to_point', 'Едет в пункт выдачи'), ('shipped', 'Отправлен'), ('ready_for_shipping', 'Готов к выдаче'), ('canceled', 'Отменен'), ('completed', 'Завершен')], default='created', max_length=200, verbose_name='Статус'),
        ),
    ]
