# Generated by Django 5.2.5 on 2025-09-07 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True, verbose_name='Почта')),
                ('telegram_id', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram Id')),
                ('telegram_username', models.CharField(blank=True, max_length=200, null=True, verbose_name='Telegram Username')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активный?')),
                ('is_staff', models.BooleanField(default=False, verbose_name='Персонал?')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='Суперюзер?')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
    ]
