# Generated by Django 5.1.6 on 2025-08-27 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Page',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=120, unique=True)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField(blank=True)),
                ('column', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Соцсети'), (2, 'Контакты'), (3, 'Информация'), (4, 'Помощь')], null=True)),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_published', models.BooleanField(default=True)),
                ('external_url', models.URLField(blank=True)),
                ('anchor', models.CharField(blank=True, max_length=120)),
                ('meta_title', models.CharField(blank=True, max_length=200)),
                ('meta_description', models.CharField(blank=True, max_length=300)),
            ],
            options={
                'verbose_name': 'Страницы футера',
                'verbose_name_plural': 'Страницы футера',
                'ordering': ('column', 'order', 'title'),
            },
        ),
    ]
