# Generated by Django 5.2.7 on 2025-10-19 13:55

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='page',
            name='meta_description',
        ),
        migrations.RemoveField(
            model_name='page',
            name='meta_title',
        ),
        migrations.AlterField(
            model_name='page',
            name='external_url',
            field=models.URLField(blank=True, validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'mailto', 'tel'])], verbose_name='Ссылка'),
        ),
    ]
