# Generated by Django 5.2.7 on 2025-10-19 14:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_remove_page_meta_description_remove_page_meta_title_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='external_url',
            field=models.CharField(blank=True, max_length=500, validators=[django.core.validators.URLValidator(schemes=['http', 'https', 'mailto', 'tel'])], verbose_name='Ссылка'),
        ),
    ]
