# Generated by Django 5.1.6 on 2025-09-01 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'ordering': ('order',), 'verbose_name': 'Социальные сети', 'verbose_name_plural': 'Социальные сети'},
        ),
    ]
