# Generated by Django 5.2.7 on 2025-10-19 14:36

import core.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_page_external_url'),
    ]

    operations = [
        migrations.AlterField(
            model_name='page',
            name='external_url',
            field=models.CharField(blank=True, max_length=500, validators=[core.models.validate_contact_url], verbose_name='Ссылка'),
        ),
    ]
