# Generated by Django 5.1.15 on 2026-09-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_integrationkey'),
    ]

    operations = [
        migrations.AlterField(
            model_name='integrationkey',
            name='key',
            field=models.CharField(choices=[('CDEK_ID', 'СДЭК — Client ID'), ('CDEK_SECRET', 'СДЭК — Secret'), ('CDEK_SENDER_CODE', 'СДЭК — код города отправителя'), ('YANDEX_MAPS_API_KEY', 'Яндекс Карты — API ключ'), ('DADATA_TOKEN', 'DaData — токен'), ('T_BANK_TERMINAL_KEY', 'Т-Банк — TerminalKey'), ('T_BANK_PASSWORD', 'Т-Банк — пароль'), ('MOYSKLAD_TOKEN', 'МойСклад — токен'), ('MOYSKLAD_ORGANIZATION_ID', 'МойСклад — организация'), ('MOYSKLAD_STORE_ID', 'МойСклад — склад'), ('MOYSKLAD_SALESCHANNEL_ID', 'МойСклад — канал продаж'), ('OZON_CLIENT_ID', 'Ozon — Client ID'), ('OZON_API_KEY', 'Ozon — API ключ'), ('WB_API_KEY', 'Wildberries — API ключ'), ('TELEGRAM_BOT_TOKEN', 'Telegram — токен бота'), ('RECAPTCHA_SITE_KEY', 'reCAPTCHA — публичный ключ'), ('RECAPTCHA_SECRET_KEY', 'reCAPTCHA — секретный ключ')], max_length=64, unique=True, verbose_name='Интеграция'),
        ),
    ]
