# Generated by Django 5.1.6 on 2025-08-21 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='order',
            name='payment_status',
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Новый'), ('paid', 'Оплачен'), ('assembled', 'Собран'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен')], db_index=True, default='created', max_length=200, verbose_name='Статус'),
        ),
    ]
