# Generated by Django 5.1.6 on 2025-08-21 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_remove_order_payment_status_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='metro',
            field=models.CharField(blank=True, max_length=100, null=True, verbose_name='Ближайшее метро'),
        ),
    ]
