# Generated by Django 5.0.1 on 2024-07-09 12:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_promotion_cart_promotion'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='product_variant',
            new_name='variant',
        ),
    ]
