# Generated by Django 5.0.1 on 2024-07-09 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_rename_product_variant_cartitem_variant'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cartitem',
            old_name='count',
            new_name='quantity',
        ),
    ]
