# Generated by Django 5.1.6 on 2025-08-21 18:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_pickuppoint_metro'),
    ]

    operations = [
        migrations.AddField(
            model_name='pickuppoint',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Отображать на главной'),
        ),
    ]
