# Generated by Django 5.2.5 on 2025-09-07 15:57

import cart.models
import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('products', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PickupPoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=50, unique=True, verbose_name='Код')),
                ('slug', models.SlugField(unique=True, verbose_name='Слаг')),
                ('title', models.CharField(max_length=120, verbose_name='Название')),
                ('city', models.CharField(db_index=True, max_length=100, verbose_name='Город')),
                ('address', models.CharField(max_length=255, verbose_name='Адрес')),
                ('metro', models.CharField(blank=True, max_length=100, null=True, verbose_name='Ближайшее метро')),
                ('lat', models.FloatField(default=0, verbose_name='Широта')),
                ('lon', models.FloatField(default=0, verbose_name='Долгота')),
                ('schedule', models.CharField(blank=True, default='', max_length=180, verbose_name='График')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('is_main', models.BooleanField(default=False, verbose_name='Отображать на главной')),
                ('sort', models.PositiveIntegerField(default=100, verbose_name='Сортировка')),
            ],
            options={
                'verbose_name': 'Пункт самовывоза',
                'verbose_name_plural': 'Пункты самовывоза',
                'ordering': ['city', 'sort', 'title'],
            },
        ),
        migrations.CreateModel(
            name='PromoCode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='Код')),
                ('discount_type', models.CharField(choices=[('percent', 'Процент'), ('fixed', 'Фиксированная сумма')], default='percent', max_length=16, verbose_name='Тип скидки')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Размер скидки')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('starts_at', models.DateTimeField(blank=True, null=True, verbose_name='Начало действия')),
                ('ends_at', models.DateTimeField(blank=True, null=True, verbose_name='Окончание действия')),
                ('usage_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Общий лимит применений')),
                ('used_count', models.PositiveIntegerField(default=0, verbose_name='Сколько раз применён')),
                ('per_user_limit', models.PositiveIntegerField(blank=True, null=True, verbose_name='Лимит на пользователя')),
                ('min_order_total', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Мин. сумма заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Промокод',
                'verbose_name_plural': 'Промокоды',
                'ordering': ('-updated_at',),
            },
        ),
        migrations.CreateModel(
            name='Cart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cart', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='carts', to='cart.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Корзина',
                'verbose_name_plural': 'Корзины',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.CharField(db_index=True, default=cart.models.gen_order_code, editable=False, max_length=20, unique=True, verbose_name='Код заказа')),
                ('ms_order_id', models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='ID Мой склад')),
                ('access_key', models.CharField(default=cart.models.gen_access_key, editable=False, max_length=48, unique=True, verbose_name='Ключ доступа')),
                ('status', models.CharField(choices=[('created', 'Новый'), ('paid', 'Оплачен'), ('assembled', 'Собран'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('canceled', 'Отменен')], db_index=True, default='created', max_length=200, verbose_name='Статус')),
                ('user_name', models.CharField(max_length=200, verbose_name='ФИО')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Почта')),
                ('order_notes', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('subtotal', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Сумма без скидок')),
                ('discount_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Скидка всего')),
                ('shipping_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Доставка')),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=10, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Итого к оплате')),
                ('payment_type', models.CharField(choices=[('online', 'Онлайн')], default='online', max_length=20, verbose_name='Тип оплаты')),
                ('payment_url', models.URLField(blank=True, verbose_name='Ссылка на оплату')),
                ('city', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Город')),
                ('pvz_address', models.CharField(blank=True, max_length=255, verbose_name='Адрес ПВЗ')),
                ('pvz_code', models.CharField(blank=True, max_length=64, verbose_name='Код ПВЗ')),
                ('date_ordered', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('promo_code', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to='cart.promocode', verbose_name='Промокод')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
                'ordering': ('-date_ordered',),
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за единицу (snapshot)')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Сумма позиции')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.order', verbose_name='Заказ')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='order_items', to='products.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказов',
            },
        ),
        migrations.CreateModel(
            name='CartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='cart.cart', verbose_name='Корзина')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.variant', verbose_name='Вариант')),
            ],
            options={
                'verbose_name': 'Товар корзины',
                'verbose_name_plural': 'Товары корзин',
                'constraints': [models.UniqueConstraint(fields=('cart', 'variant'), name='uniq_cart_variant')],
            },
        ),
    ]
