# Generated by Django 5.2.5 on 2025-09-02 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='ms_order_id',
            field=models.UUIDField(blank=True, editable=False, null=True, unique=True, verbose_name='ID Мой склад'),
        ),
    ]
