# Generated by Django 5.2.5 on 2025-09-08 22:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='updated',
            field=models.DateTimeField(auto_now=True, verbose_name='Дата обновления'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Новый'), ('confirmed', 'Подтвержден'), ('assembled', 'Собран'), ('pickup', 'Самовывоз'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('returned', 'Возврат'), ('canceled', 'Отменен'), ('auth', 'Платеж авторизован'), ('paid', 'Оплачен'), ('declined', 'Отклонен'), ('partial_return', 'Частичный возврат')], db_index=True, default='created', max_length=200, verbose_name='Статус'),
        ),
    ]
