# Generated by Django 5.2.5 on 2025-09-09 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0002_order_updated_alter_order_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='pvz_provider',
            field=models.CharField(blank=True, max_length=32, verbose_name='Провайдер ПВЗ'),
        ),
    ]
