# Generated by Django 5.2.5 on 2025-09-03 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_remove_order_amount_remove_order_is_paid_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_url',
            field=models.URLField(blank=True, verbose_name='Ссылка на оплату'),
        ),
    ]
