# Generated by Django 5.2.5 on 2025-09-09 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0003_order_pvz_provider'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='invoice',
            field=models.CharField(blank=True, max_length=32, verbose_name='Накладная'),
        ),
    ]
