# Generated by Django 5.2.5 on 2025-09-09 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='invoice',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='Накладная'),
        ),
    ]
