# Generated by Django 5.2.5 on 2025-09-03 12:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0004_order_payment_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='city',
            field=models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='Город'),
        ),
    ]
