# Generated by Django 5.2.5 on 2025-09-03 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_order_city'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='lat',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='lon',
            field=models.FloatField(blank=True, default=0, null=True, verbose_name='Долгота'),
        ),
    ]
