# Generated by Django 5.2.7 on 2025-10-21 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0005_alter_order_invoice'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='ms_order_id',
            field=models.UUIDField(blank=True, null=True, unique=True, verbose_name='ID Мой склад'),
        ),
    ]
