# Generated by Django 5.2.5 on 2025-09-03 19:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0006_alter_pickuppoint_lat_alter_pickuppoint_lon'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pickuppoint',
            name='lat',
            field=models.FloatField(default=0, verbose_name='Широта'),
        ),
        migrations.AlterField(
            model_name='pickuppoint',
            name='lon',
            field=models.FloatField(default=0, verbose_name='Долгота'),
        ),
    ]
