# Generated by Django 5.2.5 on 2025-09-03 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0007_alter_pickuppoint_lat_alter_pickuppoint_lon'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Сумма позиции'),
            preserve_default=False,
        ),
    ]
