# Generated by Django 5.2.5 on 2025-09-04 21:47

import cart.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0008_orderitem_amount'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='access_key',
            field=models.CharField(default=cart.models.gen_access_key, editable=False, max_length=48, unique=True, verbose_name='Ключ доступа'),
        ),
    ]
