# Generated by Django 5.1.15 on 2026-09-24 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0009_paymentattempt'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='admin_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Предзаказ подтверждён'),
        ),
        migrations.AddField(
            model_name='order',
            name='kind',
            field=models.CharField(choices=[('stock', 'Товары в наличии'), ('preorder', 'Предзаказ')], db_index=True, default='stock', max_length=16, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Новый'), ('confirmed', 'Подтвержден'), ('assembled', 'Собран'), ('pickup', 'Самовывоз'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('returned', 'Возврат'), ('canceled', 'Отменен'), ('auth', 'Платеж авторизован'), ('paid', 'Оплачен'), ('declined', 'Отклонен'), ('partial_return', 'Частичный возврат'), ('pending_confirmation', 'Ожидает подтверждения предзаказа')], db_index=True, default='created', max_length=200, verbose_name='Статус'),
        ),
    ]
