# Generated by Django 5.1.15 on 2026-09-24 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0010_order_admin_confirmed_at_order_kind_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Новый'), ('confirmed', 'Подтвержден'), ('assembled', 'Собран'), ('pickup', 'Самовывоз'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('returned', 'Возврат'), ('canceled', 'Отменен'), ('auth', 'Платеж авторизован'), ('paid', 'Оплачен'), ('declined', 'Отклонен'), ('partial_return', 'Частичный возврат'), ('pending_confirmation', 'Ожидает подтверждения предзаказа'), ('preorder_confirmed', 'Предзаказ подтверждён, ожидает оплаты'), ('preorder_ordered', 'Заказан у поставщика'), ('preorder_in_transit', 'Предзаказ в пути'), ('preorder_arrived', 'Предзаказ прибыл')], db_index=True, default='created', max_length=200, verbose_name='Статус'),
        ),
    ]
