# Generated by Django 5.1.15 on 2026-09-24 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0011_alter_order_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='PreorderPurchase',
            fields=[
            ],
            options={
                'verbose_name': 'Закупка предзаказа',
                'verbose_name_plural': 'Закупки предзаказов',
                'proxy': True,
                'indexes': [],
                'constraints': [],
            },
            bases=('cart.orderitem',),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='expected_delivery_from',
            field=models.DateField(blank=True, null=True, verbose_name='Ожидаем с'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='expected_delivery_to',
            field=models.DateField(blank=True, null=True, verbose_name='Ожидаем до'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='procurement_status',
            field=models.CharField(choices=[('waiting', 'Нужно заказать'), ('purchased', 'Выкуплен, в пути до MightBe'), ('at_mightbe', 'Приехал на склад MightBe'), ('cdek_transit', 'Едет по России СДЭКом'), ('completed', 'Доставлен')], db_index=True, default='waiting', max_length=24, verbose_name='Статус закупки'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='purchased_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Дата выкупа'),
        ),
        migrations.AddField(
            model_name='orderitem',
            name='supplier',
            field=models.CharField(blank=True, choices=[('touch', 'TouchBMX'), ('evo', 'EVO'), ('other', 'Другой')], db_index=True, max_length=16, verbose_name='Поставщик'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Новый'), ('confirmed', 'Подтвержден'), ('assembled', 'Собран'), ('pickup', 'Самовывоз'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('returned', 'Возврат'), ('canceled', 'Отменен'), ('auth', 'Платеж авторизован'), ('paid', 'Оплачен'), ('declined', 'Отклонен'), ('partial_return', 'Частичный возврат'), ('pending_confirmation', 'Ожидает подтверждения предзаказа'), ('preorder_confirmed', 'Предзаказ подтверждён, ожидает оплаты'), ('preorder_ordered', 'Выкупается у поставщика'), ('preorder_in_transit', 'В пути до склада MightBe'), ('preorder_arrived', 'Прибыл на склад MightBe'), ('preorder_cdek_transit', 'Едет по России СДЭКом')], db_index=True, default='created', max_length=200, verbose_name='Статус'),
        ),
    ]
