# Generated by Django 5.1.15 on 2026-09-24 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cart', '0013_add_mightbe_pickup'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='preorderpurchase',
            options={'verbose_name': 'Закупка заказа', 'verbose_name_plural': 'Закупки заказных товаров'},
        ),
        migrations.AlterField(
            model_name='order',
            name='admin_confirmed_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Под заказ подтверждён'),
        ),
        migrations.AlterField(
            model_name='order',
            name='kind',
            field=models.CharField(choices=[('stock', 'Товары в наличии'), ('preorder', 'Под заказ')], db_index=True, default='stock', max_length=16, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('created', 'Новый'), ('confirmed', 'Подтвержден'), ('assembled', 'Собран'), ('pickup', 'Самовывоз'), ('shipped', 'Отправлен'), ('delivered', 'Доставлен'), ('returned', 'Возврат'), ('canceled', 'Отменен'), ('auth', 'Платеж авторизован'), ('paid', 'Оплачен'), ('declined', 'Отклонен'), ('partial_return', 'Частичный возврат'), ('pending_confirmation', 'Ожидает подтверждения заказа'), ('preorder_confirmed', 'Под заказ подтверждён, ожидает оплаты'), ('preorder_ordered', 'Выкупается у поставщика'), ('preorder_in_transit', 'В пути до склада MightBe'), ('preorder_arrived', 'Прибыл на склад MightBe'), ('preorder_cdek_transit', 'Едет по России СДЭКом')], db_index=True, default='created', max_length=200, verbose_name='Статус'),
        ),
    ]
