# Generated by Django 5.0 on 2024-01-04 08:52

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '__first__'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_line', models.TextField(max_length=254)),
                ('city', models.CharField(max_length=50)),
                ('postal_code', models.CharField(max_length=50)),
                ('country', models.CharField(max_length=50)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='address', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Адрес',
                'verbose_name_plural': 'Адреса',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('order_id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('created', 'Создан'), ('processing', 'В обработке'), ('goes_to_point', 'Едет в пункт выдачи'), ('shipped', 'Отправлен'), ('ready_for_shipping', 'Готов к выдаче'), ('canceled', 'Отменен'), ('completed', 'Завершен')], default='created', max_length=50, verbose_name='Статус')),
                ('username', models.CharField(max_length=100, verbose_name='ФИО')),
                ('contact_phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('order_notes', models.TextField(blank=True, null=True, verbose_name='Комментарий к заказу')),
                ('receiving_method', models.CharField(blank=True, choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=50, null=True, verbose_name='Метод получения')),
                ('delivery_method', models.CharField(blank=True, choices=[('russian_post', 'Почта России'), ('sdek', 'Сдек'), ('boxberry', 'Boxberry')], max_length=50, null=True, verbose_name='Способ доставки')),
                ('pickup_location', models.CharField(blank=True, choices=[('alekseevskaya', 'Алексеевская'), ('colntsevo', 'Солнцево')], max_length=50, null=True, verbose_name='Пункт самовывоза')),
                ('tracking_code', models.CharField(blank=True, max_length=50, null=True, verbose_name='Код для отслеживания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('address', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='orders.address')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('count', models.PositiveIntegerField(default=1)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='orders.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='store.product')),
            ],
            options={
                'verbose_name': 'Товар заказа',
                'verbose_name_plural': 'Товары заказов',
            },
        ),
    ]
