# Generated by Django 5.0 on 2024-01-06 08:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0005_orderstatus_alter_order_address_alter_order_user_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderstatus',
            name='updated_at',
        ),
    ]
