# Generated by Django 5.0.1 on 2024-01-29 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0006_remove_orderstatus_updated_at'),
        ('store', '0011_warehouse_alter_attributevariant_variant_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('transaction_id', models.CharField(max_length=100, verbose_name='Номер транзакции')),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Последнее изменение')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='PaymentStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(verbose_name='Описание')),
            ],
        ),
        migrations.CreateModel(
            name='ShippingMethod',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shipping_type', models.CharField(choices=[('delivery', 'Доставка'), ('pickup', 'Самовывоз')], max_length=20, verbose_name='Тип доставки')),
                ('price', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Цена')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Способ получения',
                'verbose_name_plural': 'Способ получения',
            },
        ),
        migrations.DeleteModel(
            name='Promotion',
        ),
        migrations.AlterModelOptions(
            name='orderstatus',
            options={},
        ),
        migrations.RenameField(
            model_name='orderstatus',
            old_name='status',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='address',
            name='country',
        ),
        migrations.RemoveField(
            model_name='order',
            name='address',
        ),
        migrations.RemoveField(
            model_name='order',
            name='delivery_method',
        ),
        migrations.RemoveField(
            model_name='order',
            name='pickup_location',
        ),
        migrations.RemoveField(
            model_name='order',
            name='receiving_method',
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='payment', to='orders.order'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='payment_method',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.paymentmethod'),
        ),
        migrations.AddField(
            model_name='orderpayment',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='orders.paymentstatus'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='delivery',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='delivery', to='orders.address'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='shipping', to='orders.order'),
        ),
        migrations.AddField(
            model_name='shippingmethod',
            name='pickup',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pickup', to='store.warehouse'),
        ),
    ]
