# Generated by Django 5.1.6 on 2025-08-21 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120, unique=True)),
                ('slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('value_type', models.CharField(choices=[('text', 'Текст'), ('number', 'Число'), ('bool', 'Да/Нет')], default='text', max_length=12)),
                ('unit', models.CharField(blank=True, max_length=32)),
            ],
            options={
                'verbose_name': 'Атрибут',
                'verbose_name_plural': 'Атрибуты',
            },
        ),
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Название в ссылке')),
                ('title', models.CharField(max_length=100)),
                ('image', models.ImageField(upload_to='brends/')),
            ],
            options={
                'verbose_name': 'Бренд',
                'verbose_name_plural': 'Бренды',
            },
        ),
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, max_length=200, verbose_name='Название')),
                ('second_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Для склейки')),
                ('slug', models.SlugField(max_length=200, unique=True, verbose_name='Ссылка')),
                ('image', models.ImageField(upload_to='categories/')),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='products.category')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
                'ordering': ('name',),
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('slug', models.SlugField(max_length=200, verbose_name='Ссылка')),
                ('base_name', models.CharField(blank=True, max_length=200, null=True, verbose_name='Название')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Описание')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated', models.DateTimeField(auto_now=True, verbose_name='Дата последнего обновления')),
                ('brand', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='products.brand')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='products.category')),
            ],
            options={
                'verbose_name': 'Товар',
                'verbose_name_plural': 'Товары',
            },
        ),
        migrations.CreateModel(
            name='Variant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.UUIDField(blank=True, db_index=True, null=True, unique=True)),
                ('sku', models.CharField(blank=True, max_length=255, null=True)),
                ('price', models.DecimalField(decimal_places=2, max_digits=12)),
                ('wb_article', models.CharField(blank=True, max_length=64)),
                ('ozon_article', models.CharField(blank=True, max_length=64)),
                ('inventory', models.PositiveIntegerField(default=0)),
                ('new', models.BooleanField(default=True)),
                ('rec', models.BooleanField(default=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='products.product')),
            ],
            options={
                'verbose_name': 'Модификация',
                'verbose_name_plural': 'Модификации',
            },
        ),
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='products/gallery/', verbose_name='Изображение')),
                ('alt', models.CharField(blank=True, max_length=200, verbose_name='Alt-текст')),
                ('sort', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='products.variant')),
            ],
            options={
                'verbose_name': 'Галерея',
                'verbose_name_plural': 'Галерея',
                'ordering': ['sort', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AttributeValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value_text', models.CharField(blank=True, max_length=255)),
                ('value_number', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True)),
                ('value_bool', models.BooleanField(blank=True, null=True)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='products.attribute')),
                ('variant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attribute_values', to='products.variant')),
            ],
            options={
                'verbose_name': 'Значение атрибута',
                'verbose_name_plural': 'Значения атрибутов',
            },
        ),
        migrations.CreateModel(
            name='CategoryAttribute',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_required', models.BooleanField(default=False)),
                ('is_filterable', models.BooleanField(default=True)),
                ('is_variant', models.BooleanField(default=False)),
                ('sort_order', models.PositiveIntegerField(default=0)),
                ('attribute', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='category_usages', to='products.attribute')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_attributes', to='products.category')),
            ],
            options={
                'verbose_name': 'Атрибут категории',
                'verbose_name_plural': 'Атрибуты категорий',
                'ordering': ['sort_order', 'id'],
                'unique_together': {('category', 'attribute')},
            },
        ),
        migrations.AddIndex(
            model_name='product',
            index=models.Index(fields=['category', 'brand', 'base_name'], name='products_pr_categor_7f5542_idx'),
        ),
        migrations.AddIndex(
            model_name='variant',
            index=models.Index(fields=['product'], name='products_va_product_18d9cf_idx'),
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['product', 'sort'], name='products_im_product_6f3b2b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='attributevalue',
            unique_together={('variant', 'attribute')},
        ),
    ]
