# Generated by Django 4.2.1 on 2023-07-21 17:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Brend',
            new_name='Brand',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='brend',
            new_name='brand',
        ),
    ]
