# Generated by Django 5.1.6 on 2025-08-21 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_variant_options_alter_image_image'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='image',
            name='products_im_product_6f3b2b_idx',
        ),
        migrations.RenameField(
            model_name='image',
            old_name='product',
            new_name='variant',
        ),
        migrations.AddIndex(
            model_name='image',
            index=models.Index(fields=['variant', 'sort'], name='products_im_variant_e11ece_idx'),
        ),
    ]
