# Generated by Django 5.0 on 2023-12-30 18:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_alter_attribute_options_alter_attributevalue_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='new',
        ),
        migrations.RemoveField(
            model_name='product',
            name='recommendation',
        ),
        migrations.AddField(
            model_name='productvariant',
            name='new',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='productvariant',
            name='recommendation',
            field=models.BooleanField(default=False),
        ),
    ]
