# Generated by Django 5.0 on 2023-12-30 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_remove_product_new_remove_product_recommendation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='productvariant',
            name='name',
            field=models.CharField(default='', max_length=200, verbose_name='Вариация'),
            preserve_default=False,
        ),
    ]
