# Generated by Django 4.2.1 on 2023-08-06 22:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_product_new_alter_product_brand'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='rec',
            field=models.BooleanField(default=False, verbose_name='Рекоммендуемый?'),
        ),
    ]
