# Generated by Django 5.0 on 2023-12-31 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_attribute_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attribute',
            name='is_main',
        ),
        migrations.AddField(
            model_name='attributevalue',
            name='is_main',
            field=models.BooleanField(default=False, verbose_name='Отображать в названии'),
        ),
    ]
