# Generated by Django 5.1.6 on 2025-03-05 08:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_product_rec'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='available_andrey',
        ),
        migrations.RemoveField(
            model_name='product',
            name='available_damir',
        ),
        migrations.RemoveField(
            model_name='product',
            name='count',
        ),
        migrations.AddField(
            model_name='product',
            name='light_inventory',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Наличие LightShop'),
        ),
        migrations.AddField(
            model_name='product',
            name='mightbe_inventory',
            field=models.PositiveSmallIntegerField(default=0, null=True, verbose_name='Наличие MightBe'),
        ),
    ]
