# Generated by Django 5.1.6 on 2025-04-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_product_available_andrey_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='availability_status',
            field=models.CharField(choices=[('out_of_stock', 'Нет в наличии'), ('on_order', 'Под заказ'), ('coming_soon', 'Скоро будет'), ('in_stock', 'В наличии')], default='in_stock', max_length=20, verbose_name='Статус наличия'),
        ),
    ]
