# Generated by Django 5.0 on 2023-12-31 06:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0006_remove_attribute_is_main_attributevalue_is_main'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productvariant',
            name='name',
        ),
    ]
