# Generated by Django 5.0 on 2023-12-31 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_remove_productvariant_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='attributevalue',
            name='unit',
            field=models.CharField(blank=True, max_length=100, verbose_name='Единица измерения'),
        ),
    ]
