# Generated by Django 5.0 on 2023-12-31 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0008_attributevalue_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_part',
            field=models.BooleanField(default=False, verbose_name='Другая категория'),
        ),
    ]
